name: Deploy Website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: debian-latest
    container:
      image: node:20
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          image: node:20

      - run: pnpm ci
      - run: pnpm run build

      - name: Install Wireguard
        run: |
          sudo apt-get update 
          sudo apt-get install -y wireguard sshpass
      - name: Set up WireGuard config
        run: |
          echo "${{ secrets.WG_CONFIG }}" > wg0.conf
          sudo chmod 600 wg0.conf

      - name: Start WireGuard
        run: |
          sudo wg-quick up ./wg0.conf

      - name: Deploy to Server using SCP over VPN
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./dist/* ${{secrets.SSH_USER}}@${{ secrets.SSH_HOST1 }}:~/node-app

      - name: Restart Server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no student@10.199.30.2 "cd ~/node-app && pnpm install && pm2 restart all"

